#!/bin/sh
# Allows for dmenu_run to be used without swallowing the terminal

killall bspswallow
dmenu_run

# Hang until dmenu is closed
while pidof dmenu; do continue
done

#If you frequently use dmenu_run without spawing a window commentout this while loop and uncomment the commented out part below
bspc subscribe node_add | while read -r event; do
bspswallow & exit
done

# sleep 2
# bspswallow & exit
